name: impdar
channels:
  - conda-forge
  - defaults
dependencies:
  - nose
  - "numpy>=1.12.0"
  - "scipy>=0.19.1,<1.8.0"
  - segyio
  - "h5py>=3.0.0"
  - netCDF4
  - gdal
  - pyqt
  - pyproj
  - spyder
  - jupyter
  - seaborn
  - pandas
  - pip
  - pip:
    - PyQt5
    - impdar
